name: CI Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      ENCODED_STRING: ${{ secrets.SLIIT_EATS_KEY_JKS }}
      SLIIT_EATS_KEY_PASSWORD: ${{ secrets.SLIIT_EATS_KEY_PASSWORD }}
      SLIIT_EATS_ALIAS_PASSWORD: ${{ secrets.SLIIT_EATS_ALIAS_PASSWORD }}
      APP_ENV: STAGING
    steps:
      - name: Decode Key
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/key.jks
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'
      - name: Create env file
        run: |
          touch .env
          echo SLIIT_EATS_FIREBASE_API_KEY=${{ secrets.SLIIT_EATS_FIREBASE_API_KEY }} >> .env
          echo SLIIT_EATS_FIREBASE_APP_ID=${{ secrets.SLIIT_EATS_FIREBASE_APP_ID }} >> .env
          echo SLIIT_EATS_FIREBASE_PROJECT_ID=${{ secrets.SLIIT_EATS_FIREBASE_PROJECT_ID }} >> .env
          echo SLIIT_EATS_FIREBASE_BUCKET=${{ secrets.SLIIT_EATS_FIREBASE_BUCKET }} >> .env
          echo SLIIT_EATS_FCM_SENDER_ID=${{ secrets.SLIIT_EATS_FCM_SENDER_ID }} >> .env
          cat .env
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk